# SPDX-FileCopyrightText: 2026 The Refinery Authors <https://refinery.tools/>
#
# SPDX-License-Identifier: Apache-2.0

file.encoding=UTF-8
group=tools.refinery.ibex
org.gradle.unsafe.isolated-projects=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
# Commit in https://github.com/ibex-team/ibex-lib the upstream version tag must point to.
tools.refinery.ibex.commit=356cc59e3f023b55d83353c61a52a5f1857c49dd
version=2.9.1-2
