/*
 * SPDX-FileCopyrightText: 2026 The Refinery Authors <https://refinery.tools/>
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package tools.refinery.ibex.gradle;

import org.cyclonedx.Version;
import org.cyclonedx.exception.GeneratorException;
import org.cyclonedx.generators.BomGeneratorFactory;
import org.cyclonedx.model.Bom;
import org.cyclonedx.model.Commit;
import org.cyclonedx.model.Component;
import org.cyclonedx.model.Composition;
import org.cyclonedx.model.Dependency;
import org.cyclonedx.model.License;
import org.cyclonedx.model.LicenseChoice;
import org.cyclonedx.model.Metadata;
import org.cyclonedx.model.Pedigree;
import org.cyclonedx.model.license.Expression;
import org.cyclonedx.parsers.JsonParser;
import org.gradle.api.GradleException;
import org.gradle.api.DefaultTask;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.ListProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.OutputFile;
import org.gradle.api.tasks.TaskAction;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates a CycloneDX SBOM describing the upstream code we bundle.
 * <p>
 * IBEX and the interval arithmetic libraries are vendored into our artifacts instead of being resolved as Maven
 * dependencies, so nothing in the dependency graph refers to them and no dependency-derived SBOM (in particular, one
 * generated by the CycloneDX Gradle plugin) can describe what our artifacts actually contain.
 */
public abstract class GenerateCycloneDxBomTask extends DefaultTask {
    private static final Version SPEC_VERSION = Version.VERSION_17;
    private static final String IBEX_REPOSITORY = "https://github.com/ibex-team/ibex-lib";
    private static final String OUR_LICENSE = "Apache-2.0";
    private static final String IBEX_LICENSE = "LGPL-3.0-or-later";

    /**
     * {@return the Maven group of the artifact the SBOM is published alongside}
     */
    @Input
    public abstract Property<String> getArtifactGroup();

    /**
     * {@return the Maven artifact ID of the artifact the SBOM is published alongside}
     */
    @Input
    public abstract Property<String> getArtifactName();

    /**
     * {@return the Maven version of the artifact the SBOM is published alongside}
     */
    @Input
    public abstract Property<String> getArtifactVersion();

    /**
     * {@return the upstream IBEX version the artifact was built from}
     */
    @Input
    public abstract Property<String> getIbexVersion();

    /**
     * {@return the upstream IBEX commit the artifact was built from}
     */
    @Input
    public abstract Property<String> getIbexCommit();

    /**
     * {@return the interval arithmetic libraries the artifact distributes}
     */
    @Input
    public abstract ListProperty<IntervalLib> getIntervalLibs();

    /**
     * {@return whether the upstream code is distributed as native libraries, as opposed to source code in the
     * sources jar only}
     */
    @Input
    public abstract Property<Boolean> getBundledAsBinary();

    @OutputFile
    public abstract RegularFileProperty getOutputFile();

    @TaskAction
    public void generate() throws GeneratorException, IOException {
        var bom = new Bom();
        var metadata = new Metadata();
        // The metadata is created with the current time, but we drop it -- along with the serial number we never
        // set -- so that the SBOM stays byte-for-byte reproducible.
        metadata.setTimestamp(null);
        metadata.setComponent(createRootComponent());
        bom.setMetadata(metadata);

        var ibex = createIbexComponent();
        bom.addComponent(ibex);
        var ibexDependency = new Dependency(ibex.getBomRef());
        var libraryDependencies = new ArrayList<Dependency>();
        for (var intervalLib : getIntervalLibs().get()) {
            var libraryComponent = createLibraryComponent(intervalLib, intervalLib.getLibrary());
            bom.addComponent(libraryComponent);
            ibexDependency.addDependency(new Dependency(libraryComponent.getBomRef()));
            // The libraries the interval arithmetic library itself relies on, e.g., MathLib for GAOL. Libraries
            // without any are left out of the dependency graph instead of being recorded with an empty list.
            if (intervalLib.getDependencies().isEmpty()) {
                continue;
            }
            var libraryDependency = new Dependency(libraryComponent.getBomRef());
            for (var dependency : intervalLib.getDependencies()) {
                var dependencyComponent = createLibraryComponent(intervalLib, dependency);
                bom.addComponent(dependencyComponent);
                libraryDependency.addDependency(new Dependency(dependencyComponent.getBomRef()));
            }
            libraryDependencies.add(libraryDependency);
        }

        var artifactPurl = getArtifactPurl();
        var artifactDependency = new Dependency(artifactPurl);
        artifactDependency.addDependency(new Dependency(ibex.getBomRef()));
        bom.addDependency(artifactDependency);
        bom.addDependency(ibexDependency);
        libraryDependencies.forEach(bom::addDependency);

        // Maven dependencies of the artifact are described by its POM instead of this SBOM, which only records the
        // upstream code we bundle ourselves.
        var composition = new Composition();
        composition.setAggregate(Composition.Aggregate.INCOMPLETE);
        composition.addDependency(new org.cyclonedx.model.BomReference(artifactPurl));
        bom.setCompositions(List.of(composition));

        writeBom(bom);
    }

    private Component createRootComponent() {
        var component = new Component();
        component.setType(Component.Type.LIBRARY);
        component.setBomRef(getArtifactPurl());
        component.setGroup(getArtifactGroup().get());
        component.setName(getArtifactName().get());
        component.setVersion(getArtifactVersion().get());
        component.setPurl(getArtifactPurl());
        // Everything published under these coordinates, including the source code in the sources jar, which is why
        // this expression can be longer than the {@code Bundle-License} header of the jar itself.
        var licenses = new ArrayList<String>();
        licenses.add(OUR_LICENSE);
        licenses.add(IBEX_LICENSE);
        for (var intervalLib : getIntervalLibs().get()) {
            licenses.add(intervalLib.getLicenseSpdxId());
        }
        component.setLicenses(expression(String.join(" AND ", licenses)));
        return component;
    }

    private Component createIbexComponent() {
        var commit = getIbexCommit().get();
        var component = new Component();
        component.setType(Component.Type.LIBRARY);
        component.setBomRef("pkg:github/ibex-team/ibex-lib@" + commit);
        component.setName("ibex-lib");
        component.setVersion(getIbexVersion().get());
        component.setPublisher("IBEX Team");
        // Required even in the main artifact, whose jar contains the Java bindings generated from these sources.
        component.setScope(Component.Scope.REQUIRED);
        component.setPurl(component.getBomRef());
        component.setLicenses(license(IBEX_LICENSE));

        var pedigreeCommit = new Commit();
        pedigreeCommit.setUid(commit);
        pedigreeCommit.setUrl(IBEX_REPOSITORY + "/tree/" + commit);
        var pedigree = new Pedigree();
        pedigree.setCommits(List.of(pedigreeCommit));
        pedigree.setNotes(getBundledAsBinary().get()
                ? "Built from the sources of this commit, without the vendored SoPlex sources, which are left out " +
                "because of their ZIB Academic License. SoPlex is not built into the native libraries, because " +
                "IBEX is built with its default LP_LIB=none setting."
                : "The sources of this commit, without the vendored SoPlex sources, which are left out because of " +
                "their ZIB Academic License, are embedded in the sources jar published under the same coordinates.");
        component.setPedigree(pedigree);
        return component;
    }

    private Component createLibraryComponent(IntervalLib intervalLib, IntervalLib.Library library) {
        var component = new Component();
        component.setType(Component.Type.LIBRARY);
        component.setBomRef(library.purl());
        component.setName(library.name());
        component.setVersion(library.version());
        component.setPurl(library.purl());
        component.setLicenses(license(intervalLib.getLicenseSpdxId()));
        // In the main artifact, the library is only present as source code, which nothing can call, so it is
        // optional there. The platform-specific artifacts link it into their native libraries, which makes it
        // required for them.
        component.setScope(getBundledAsBinary().get() ? Component.Scope.REQUIRED : Component.Scope.OPTIONAL);
        var descriptionFormat = getBundledAsBinary().get()
                ? "Vendored in the IBEX sources under %s and built into the native libraries of this artifact."
                : "Vendored in the IBEX sources under %s, which are embedded in the sources jar published under " +
                "the same coordinates. Only the platform-specific artifacts distribute it in binary form.";
        component.setDescription(descriptionFormat.formatted(intervalLib.getVendoredPath()));
        return component;
    }

    private String getArtifactPurl() {
        return "pkg:maven/%s/%s@%s".formatted(getArtifactGroup().get(), getArtifactName().get(),
                getArtifactVersion().get());
    }

    private static LicenseChoice expression(String value) {
        var licenseChoice = new LicenseChoice();
        licenseChoice.addExpression(new Expression(value));
        return licenseChoice;
    }

    private static LicenseChoice license(String spdxId) {
        var license = new License();
        license.setId(spdxId);
        var licenseChoice = new LicenseChoice();
        licenseChoice.addLicense(license);
        return licenseChoice;
    }

    private void writeBom(Bom bom) throws GeneratorException, IOException {
        var json = BomGeneratorFactory.createJson(SPEC_VERSION, bom).toJsonString();
        // The model classes let us build an SBOM the schema rejects, e.g., with a malformed package URL, so we check
        // what we are about to publish instead of trusting the generator.
        var errors = new JsonParser().validate(json, SPEC_VERSION);
        if (!errors.isEmpty()) {
            var messages = errors.stream().map(Throwable::getMessage).collect(Collectors.joining("\n  "));
            throw new GradleException("Generated SBOM is not valid CycloneDX %s:%n  %s"
                    .formatted(SPEC_VERSION.getVersionString(), messages));
        }
        var outputPath = getOutputFile().get().getAsFile().toPath();
        Files.createDirectories(outputPath.getParent());
        Files.writeString(outputPath, json + "\n", StandardCharsets.UTF_8);
    }
}
